<a href="https://colab.research.google.com/github/vasudevanmk/M-L-A-Z/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network For Regression

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [6]:
dataset = pd.read_excel('/content/drive/MyDrive/Machine Learning A-Z /Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(dataset)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [9]:
print(X,y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] [463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 98102.8125
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 2283.1460
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 236.0152
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 216.4341
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 196.7196
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 175.1253
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 155.1262
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 136.1695
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 119.7183
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 106.8924
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 94.3030
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - lo

### Predicting the results of the Test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.37 431.23]
 [462.52 460.01]
 [466.1  461.14]
 ...
 [473.24 473.26]
 [440.02 438.  ]
 [459.25 463.28]]
